version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    networks:
      - monitoring
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    networks:
      - monitoring
    ports:
      - 3000:3000
    environment:
      GF_DATASOURCE: prometheus

  loki:
    image: grafana/loki:latest
    networks:
      - monitoring
    ports:
      - 3100:3100

  shoe_hub:
    build:
      context: ./ShoeHubV2
      dockerfile: Dockerfile
    networks:
      - monitoring
    ports:
      - 8080:8080

networks:
  monitoring:
    external: false
